- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exuist or not
    # when you want to run linux commands directly i.e in the case ansible module not available.
    # when the user does not exists, ansible treating this failure and comout by default.
    # ignore_errors: true
    ansible.builtin.command: id roboshop
    register: output #output is variable name
    ignore_error: true
  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"
